### ISSUE TITLE
Pico 2 or pimoroni pico plus 2 support?

### ISSUE THREAD

**Issue by pketelaar** [evansm7/pico-mac#9] opened 2024-08-09 23:15 UTC
Any chance of Pico 2 or Pimoroni Pico 2 Plus support for higher ram/storage?

 https://shop.pimoroni.com/products/pimoroni-pico-plus-2?variant=42092668289107

**Comment by evansm7** [comment] 2024-08-10 11:12
Duplicate of #7 ! :) but yea, on the radar.

**Closed** 2024-08-10 11:12 UTC
